### PR TITLE
test

### PR DESCRIPTION
**Pull request by alexandrebouthinon**

### CODE REVIEW

**Comment by alexandrebouthinon** [comment]
toto

**Comment by alexandrebouthinon** [comment]
TATA

**Comment by kuzzle** [comment]
gros test

**Comment by kuzzle** [comment]
grogrogro

**Comment by kuzzle** [comment]
<h2>Snippets tests reports</h2><span>  <a href='https://docs-v2.kuzzle.io/reports/js/1'>      </a></span>&nbsp;<span>  <a href='https://docs-v2.kuzzle.io/reports/go/1'>      </a></span>

**Pull request closed without merging**
